# Generated by Django 4.0.6 on 2022-07-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(verbose_name='Preço por Hora')),
                ('vagas', models.PositiveIntegerField(verbose_name='Número de Vagas')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCadastrado',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrada', models.DateField(auto_now_add=True, verbose_name='Horário de Entrada')),
                ('horario_saida', models.DateField(verbose_name='Horário de Saída')),
                ('pago', models.BooleanField()),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='codigo.usuariocadastrado')),
            ],
        ),
    ]
