# Generated by Django 4.0.6 on 2022-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0004_alter_ficha_horario_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='desconto',
            field=models.FloatField(default=30, verbose_name='Desconto para Usuário Cadastrado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='preco',
            field=models.PositiveIntegerField(verbose_name='Preço por Hora'),
        ),
    ]
