# Generated by Django 4.0.6 on 2022-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0005_config_desconto_alter_config_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='desconto',
            field=models.FloatField(default=30, verbose_name='Desconto para Usuário Cadastrado'),
        ),
    ]
