# Generated by Django 4.0.6 on 2022-07-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0002_alter_ficha_horario_saida_alter_ficha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='codigo.usuariocadastrado'),
        ),
    ]
