# Generated by Django 4.0.6 on 2022-07-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0003_alter_ficha_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='horario_entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horario_saida',
            field=models.DateTimeField(null=True, verbose_name='Horário de Saída'),
        ),
    ]
