# Generated by Django 4.0.6 on 2022-07-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0007_alter_config_desconto_alter_config_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
